version: 2

jobs:
  test-crystal: &test-template
    docker:
      - image: crystallang/crystal:0.31.1
    steps:
      - checkout
  test:
    <<: *test-template
    steps:
      - checkout
      - run: shards
      - run: ./bin/ci
  test-coverage:
    docker:
      - image: hanneskaeufler/crystal-kcov:0.27.2-v36
    steps:
      - checkout
      - run: ./bin/test-coverage
  test-mutations:
    <<: *test-template
    steps:
      - checkout
      - run: make bin
      - run: ./bin/test-mutations

workflows:
  version: 2
  ci:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test
      - test-mutations
