version: 2

jobs:
  test-crystal: &test-template
    docker:
      - image: crystallang/crystal:0.27.0
    steps:
      - checkout
      - run: shards
      - run: ./bin/static-analysis
      - run: ./bin/code-style
      - run: SPEC_VERBOSE=1 ./bin/test
  test-crystal-0.27.0:
    <<: *test-template
    docker:
      - image: crystallang/crystal:0.27.0
  test-coverage:
    docker:
      - image: crystallang/crystal:0.27.0
    steps:
      - checkout
      - run: apt-get update && apt-get -y install curl
      - run: shards
      - run: SPEC_VERBOSE=1 ./bin/test-coverage
  test-mutations:
    docker:
      - image: crystallang/crystal:0.27.0
    steps:
      - checkout
      - run: shards
      - run: make bin
      - run: ./bin/test-mutations

workflows:
  version: 2
  ci:
    jobs:
      - test-crystal-0.27.0
      - test-coverage
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test-crystal-0.27.0
      - test-coverage
      - test-mutations
